### ISSUE TITLE
Add 10-12 dialogues from Hollywood Movies to the Dataset

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#111]
<div> <h1 align="center">Please Follow all the rules I mentioned, then send PRs🙏. </h3> </div>
<div> <h3 align="center">It is important that you do this task when you are a movie enthusiast, but please do not copy it from another website without knowing what it says 🙏. </h3> </div>

<h4 align="left">How to do that? </h4>
👇

* Read [This](https://github.com/Subham-Maity/StockOfSentence#-3-could-you-please-tell-me-how-i-can-add-my-sentence-to-this-website--) 👈

<h4 align="left">Rules: </h4>

**1.** At least 10 more sentences from the **Hollywood Movie's Dialogue or Quotes** should be added 🎥
 - Make sure you don't include any religious-type sentences or unnecessary sentences. Instead, use normal sentences that can improve people's vocabulary. ⬅️~~~~~~~~👈♦️(**Important Rule**)♦️

**2.** You should check the **dataset** and how it's written, then **maintain the format** and add whatever you want but you should also **explain the meaning of the sentences**. 📝~~~~~~~~👈♦️(**Important Rule**)♦️

**3.** For better understanding, please must use **emojis with sentences** 🙏~~~~~~~~👈♦️(**Important Rule**)♦️

**4.** The sentence should not be repeated. Please check the dataset by typing ```ctrl+f``` in any text editor or IDE to see whether it has already been present in the dataset or not ⁉️

**5.** You can correct **other's sentences** 🙌

**6.** Dialogue should be **small-sized** 🙏

**7.** The Hinglish(a blend of Hindi and English) meaning can be substituted for the English meaning of the Hollywood movie Dialogues or Quotes if you are ```Indian```  😉

_Note: Don't change the function or pattern of the data_ ❌~~~~~~~~👈♦️(**Important Rule**)♦️

#### Note: You can get a better understanding of the code by reading the description ```README.md``` of the repo.✌️

<p align="center" >
        <img src="https://user-images.githubusercontent.com/97989643/195846129-7710e773-ed01-4c6e-9cbc-c4af061e80d2.gif" width="600" height="295" /> </p>

**Comment by pratik2315** [comment]
hey @Subham-Maity ! can I work on this issue?

**Comment by Subham-Maity** [comment]
@pratik2315 Sure

**Comment by S-YUVARAJ** [comment]
Please assign this to me
I am very new to open source and very interested to contribute to the open source community, this will be a very good opportunity for me and I will be forever grateful to you

Thanking You in advance 
Regards
S Yuvaraj

**Comment by Subham-Maity** [comment]
@pratik2315 @S-YUVARAJ **In this particular issue anyone can contribute. There is no limitation**

**Comment by abhishekr700** [comment]
Please assign me too @Subham-Maity

**Comment by Subham-Maity** [comment]
@abhishekr700 Sure

**Comment by GitArya27** [comment]
please assign me this too @Subham-Maity

**Comment by ANMOLYADAV1402** [comment]
please assign me this too @Subham-Maity

**Comment by Subham-Maity** [comment]
@GitArya27 Sure!

**Comment by Subham-Maity** [comment]
@ANMOLYADAV1402 Sure!

**Comment by Shyamlee-1207** [comment]
Please assigm me this issue @Subham-Maity

**Comment by Subham-Maity** [comment]
> Please assign me this issue @Subham-Maity 

Sure

**Comment by kaliappan01** [comment]
Please assign this issue to me @Subham-Maity

**Comment by komalsoni4** [comment]
please assign me this

**Comment by Subham-Maity** [comment]
@kaliappan01 Sure!

**Comment by Subham-Maity** [comment]
> please assign me this

@komalsoni4 Sure!

**Comment by sunridden** [comment]
Please assign this to me @Subham-Maity

**Comment by GeekyMax-Ytiam** [comment]
@sunridden do it

**Comment by harshpailkar** [comment]
Can i work on this ? @Subham-Maity

**Comment by Subhasish-Negel** [comment]
@harshpailkar Sure! Do it!

**Comment by Subhasish-Negel** [comment]
> please assign me this too @Subham-Maity

Do it!

**Comment by Subhajit-Bera** [comment]
@Subham-Maity Assign this to me

**Comment by Subham-Maity** [comment]
@Subhajit-Bera do it!
