### ISSUE TITLE
Adding additional dialogues

### ISSUE THREAD

**Issue by gregoris-io** [Subham-Maity/StockOfSentence#124]
I was thinking off adding additional dialogues to your data set.

Thoughts I've had include:
Philosophers,
Military Figures,
Heads of states, etc..

I do not know how they would fit into your data set categorization though.

**Comment by GeekyMax-Ytiam** [comment]
@gregoris-io It's an open-source project so you can modify it as you want. You can use it for your personal use and after modification, simply create a pull request. We will inform you if any changes are needed.

**Comment by gregoris-io** [comment]
@GeekyMax-Ytiam, would it be possible for you to add the hacktoberfest tag for me please?
