### ISSUE TITLE
Add Contributing.md file

### ISSUE THREAD

**Issue by gregoris-io** [Subham-Maity/StockOfSentence#131]
Can I create a very limited contribution file, in which it is easy and clear how to fork the project, set it up locally, and push to the remote repository? 

I feel this will make it easier for new developers to get involved in the project.

Finally, if approved, could you add a "hacktoberfest" , and "hacktoberfest-accepted" label for me?

Thanks

**Comment by GeekyMax-Ytiam** [comment]
@gregoris-io **Yes the idea is great, so do it**
