### ISSUE TITLE
Enhance the Sound Button Design 

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#14]
<div><h1> Enhance the animated sound button with an appropriate theme for when someone clicks it, a start visual should appear. When the sound button is paused, it should appear as a pause visual  </h1><div>

## Now: 

![image](https://user-images.githubusercontent.com/97989643/195409998-f9ea1da9-e73e-441c-87c4-cc66f25e8608.png)

### [Check this for Reference](https://codepen.io/wazp/pen/NwwbvW)

<table>

![image](https://user-images.githubusercontent.com/97989643/195410514-afc4e332-bc14-42a0-ad55-6f2128b63c07.png)

![image](https://user-images.githubusercontent.com/97989643/195410725-7bf918fd-4374-4e62-8de8-48eb5e209aba.png)

</table>

**Comment by rohitsinghind** [comment]
Hello sir, Can you assign this issue to me?

**Comment by Subham-Maity** [comment]
@rohitsinghind Sure!

**Comment by rohitsinghind** [comment]
done

**Comment by Subham-Maity** [comment]
@rohitsinghind  **Could you please tell me what changes you made?** 
**Could you please send me the pull request?**

**Comment by rohitsinghind** [comment]
edited the onClick function for sound button

**Comment by rohitsinghind** [comment]
also sent the pull request, you can check it out
