### ISSUE TITLE
Fix The Mobile View & Also Fixed the Desktop zoom Issue 

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#18]

**Comment by mnosov622** [comment]
Hi @Subham-Maity !

I would love to work on this issue. Could you please clarify what exactly needs to be fixed?

For now I see that there is no mobile adaptation.

Thank you.

**Comment by Subham-Maity** [comment]
Hi @mnosov622 !
**When someone zooms in or out on desktop view all the elements are moved according to their x and y axis this should be fixed**




https://user-images.githubusercontent.com/97989643/195522942-513f1fef-ec5b-4b6f-ae41-fc65460de412.mp4

**Mobile view also same problem** 



https://user-images.githubusercontent.com/97989643/195523006-952ef634-3264-41d0-9482-3fc1171a052b.mp4
