### ISSUE TITLE
Enhance the Sound Button Design

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#20]
<div><h1> Enhance the animated sound button with an appropriate theme for when someone clicks it, a start visual should appear. When the sound button is paused, it should appear as a pause visual  </h1><div>

## Now: 

![image](https://user-images.githubusercontent.com/97989643/195409998-f9ea1da9-e73e-441c-87c4-cc66f25e8608.png)

### [Check this for Reference](https://codepen.io/wazp/pen/NwwbvW)

<table>

![image](https://user-images.githubusercontent.com/97989643/195410514-afc4e332-bc14-42a0-ad55-6f2128b63c07.png)

![image](https://user-images.githubusercontent.com/97989643/195410725-7bf918fd-4374-4e62-8de8-48eb5e209aba.png)

</table>

**Comment by jsvigneshkanna** [comment]
Please assign to my name

**Comment by Subham-Maity** [comment]
@jsvigneshkanna Sure!

**Comment by Subham-Maity** [comment]
@jsvigneshkanna Thank you so much!
