### ISSUE TITLE
Add 10-12 Interesting sentences with Meaning 

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#21]
**1. At least 10-12 more interesting sentences should be added** 
**2. You should check the dataset and how it's written, then maintain the format and add whatever you want. However, you should also explain the meaning of the sentence.**  
**3. For better understanding, use emojis** 

```Note: You can get a better understanding of the code by reading the description README.md.```

**Comment by rajnish254** [comment]
kindly Assign me that issue
Thanks

**Comment by Subham-Maity** [comment]
@rajnish254 Sure!

**Comment by jayantchaudhari18** [comment]
Hey, @Subham-Maity can you assign this issue to me? I would love to work on it.

**Comment by Subham-Maity** [comment]
@jayantchaudhari18 Sure

**Comment by jayantchaudhari18** [comment]
Please merge my PR.
