### ISSUE TITLE
Add 10-12 Sentences from Movies Dialogue with Clear Meaning

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#27]
**1. At least 10-12 more sentences from the movie's dialogue should be added** 
**2. You should check the dataset and how it's written, then maintain the format and add whatever you want. However, you should also explain the meaning of the sentence.**  
**3. For better understanding, please must use emojis with sentences** 

_Note: Don't change the function or pattern of the data_ 

```Note: You can get a better understanding of the code by reading the description README.md.```

**Comment by PrashantIndurkar** [comment]
hi @Subham-Maity i want to work on this can u assign to me

**Comment by PrashantIndurkar** [comment]
hi @Subham-Maity I want to work on this can u assign it to me

**Comment by Subham-Maity** [comment]
Sure @PrashantIndurkar !

**Comment by PrashantIndurkar** [comment]
@Subham-Maity  can you point me to where I should go for changing  "movie's dialogue"

**Comment by Subham-Maity** [comment]
Inside script.js 
![image](https://user-images.githubusercontent.com/97989643/195665106-9cf8cf0c-c95c-4c35-9f5e-6c443405cc10.png)

You need to understand the dataset, and how sentences are written, then add your movie's dialect based on the format 

![image](https://user-images.githubusercontent.com/97989643/195665307-bda4234a-b2f4-4914-beaa-514a9f04f1c6.png)

**Comment by jayantchaudhari18** [comment]
Hey @Subham-Maity can you assign this issue to me.

**Comment by Subham-Maity** [comment]
@jayantchaudhari18 Sure!

**Comment by jayantchaudhari18** [comment]
Please check my PR.
