### ISSUE TITLE
Write 10 Sentences with Clear Meaning from Movie Dialogue

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#30]
**1. At least 10-12 more sentences from the movie's dialogue should be added** 
**2. You should check the dataset and how it's written, then maintain the format and add whatever you want. However, you should also explain the meaning of the sentence.**  
**3. For better understanding, please must use emojis with sentences** 

_Note: Don't change the function or pattern of the data_ 

```Note: You can get a better understanding of the code by reading the description README.md.```

**Comment by ShrinathPawar** [comment]
I would like to work on this issue. Will you assign this issue to me?

**Comment by Subham-Maity** [comment]
@ShrinathPawar Sure!

**Comment by TGFlame** [comment]
Could I also work on this? Your website looks interesting and I have watched a decent amount of movies.

**Comment by Subham-Maity** [comment]
@TGFlame Sure! Contributions of any kind are welcome!

**Comment by Radiosnack** [comment]
Hey ! Can I work on this issue?

**Comment by Subham-Maity** [comment]
@Radiosnack Sure!
