### ISSUE TITLE
Increase The Size of the Music Button and Place it in an Appropriate Place so that it looks Good 

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#31]
**Don't change the button design just increase the size of the music button and place it in an appropriate place so that it looks good** 

![image](https://user-images.githubusercontent.com/97989643/195863465-87ea317c-a58b-4e04-909c-5a2af8e9be2a.png)

**Comment by MoitreyoChak** [comment]
Hey,
I would like to work on this task.

**Comment by Nimesh-21** [comment]
Please assign this task to me. I would like to work on it.

**Comment by jayantchaudhari18** [comment]
Hey @Subham-Maity  please assign this issue to me

**Comment by Subham-Maity** [comment]
@MoitreyoChak Sure!

**Comment by Subham-Maity** [comment]
@Nimesh-21 Sure!

**Comment by darshikaguptaa** [comment]
Hey @Subham-Maity I would like to work on this issue. Please assign it to me

**Comment by Subham-Maity** [comment]
@darshikaguptaa Sure!

**Comment by jayantchaudhari18** [comment]
> Hey @Subham-Maity please assign this issue to me

can you assign me

**Comment by Subham-Maity** [comment]
@jayantchaudhari18 Sure!
