### ISSUE TITLE
Fix Mobile View 

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#38]
## **Fix Mobile View** 

![image](https://user-images.githubusercontent.com/97989643/195852995-191b6843-21fa-41e0-9cab-d6eca0d7891a.png)

**Comment by Abhijeet03s** [comment]
@Subham-Maity I want to work on this issue.
Also, the background animation is soo dope.

**Comment by Subham-Maity** [comment]
@Abhijeet03s Sure!

**Comment by Abhijeet03s** [comment]
@Subham-Maity  check this out:
I added a breakpoint at 480px for mobile view:

[Stock-Of-Sentence.webm](https://user-images.githubusercontent.com/107188710/196104313-9bab5fc0-cbbf-4324-a7a2-9de59b851585.webm)

**Comment by Subham-Maity** [comment]
@Abhijeet03s Cool! Can you send me a pull request?

**Comment by Abhijeet03s** [comment]
> @Abhijeet03s Cool! Can you send me a pull request?

Yes sure.
