### ISSUE TITLE
Update play/pause of audio.

### ISSUE THREAD

**Issue by BoneNzy** [Subham-Maity/StockOfSentence#77]
## The audio does not pause when you exit the quote window!
- I don't know whether it is a feature or a bug, but even after exiting from the quote window and going back to the landing page, the audio does not end.

### We can add a feature to pause whenever this window is closed.
![tinywow_Screenshot of quoteWindow_6932742](https://user-images.githubusercontent.com/109333119/196520153-dfbdc5e9-8df4-4e28-a78e-51478f44e8c2.png)

### Also, I have an idea of adding a feature to pause and play audio by pressing the space bar.

**Comment by a-u-m** [comment]
@Subham-Maity Hey, I would like to work on this issue.

**Comment by Subham-Maity** [comment]
@a-u-m sure!

**Comment by BoneNzy** [comment]
> @Subham-Maity Hey, I would like to work on this issue.

I have actually solved the issue in my local computer. But you can fix the main repo. If you need any help, you can reach out ✌️

**Comment by Subham-Maity** [comment]
> > @Subham-Maity Hey, I would like to work on this issue.
> 
> I have actually solved the issue in my local computer. But you can fix the main repo. If you need any help, you can reach out ✌️

@BoneNzy  sent me a pull request

**Comment by a-u-m** [comment]
@Subham-Maity btw I am done too

**Comment by Subham-Maity** [comment]
> @Subham-Maity btw I am done too
> 

Sent me a pull request

**Comment by BoneNzy** [comment]
Seems like its resolved

**Comment by Subham-Maity** [comment]
@BoneNzy **It is greatly appreciated that you kept me informed about the bugs and that you also spent time on the project.**
