### ISSUE TITLE
Want to Add a Background Sound 

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#8]
**1. As a function, make an appropriate button in the right-down corner so that background music will start automatically when the button is pressed.** 

**2. Add any background music like the description - README.md**

![Screenshot 2022-10-10 134155](https://user-images.githubusercontent.com/97989643/194823275-0ac7393e-2f1a-4496-b170-b6020f277159.png)

**Comment by Adw8** [comment]
Hi @Subham-Maity, Can I work on this issue?

**Comment by Subham-Maity** [comment]
@Adw8 Sure!

**Comment by Adw8** [comment]
@Subham-Maity could you tell me how to get the website running in dev mode? what command should I use?

**Comment by Subham-Maity** [comment]
@Rkpani05 Can you elaborate on what you mean by website running in development mode  

However, you can work on this project like this 
1. **Fork this repo** 
2. **Clone this repo**
3. Give a **branch name** - ```git branch your_branch_name```
4. Check your **branch** - ```git checkout your_branch_name```
5. For checking **status** - ``` git status```
6. **Adding the changes** - ```git add .```
7. **Commit** - ```git commit -m"your changes"```
8. **Push the changed files** - ```git push origin your_branch_name```
9. Then open your repo check changes and click on **compare & pull request** and write what questions and answers you added then commit 

10. I will merge the branch after checking all the questions, answers and explanation

**Comment by Adw8** [comment]
@Subham-Maity I've followed the steps you mentioned, what I meant was how I would be able to see the changes I made, but clicking on the html file solved it.

**Comment by Subham-Maity** [comment]
Hey, @Adw8 Any update?

**Comment by Subham-Maity** [comment]
@Adw8 **I have already implemented this feature, but if you want to enhance it, you can improve the time complexity of the function or customize the button.**
