### ISSUE TITLE
Text Show and Disappear Features 🤔

### ISSUE THREAD

**Issue by GeekyMax-Ytiam** [Subham-Maity/StockOfSentence#84]
**1. The music starts and stops when you press the spacebar so a text message can be added that says "if you press the space bar music will begin." when we enter the site, then disappears automatic**

**2. We can use an alert also**

**Comment by JatinSingh08** [comment]
Hey @GeekyMax-Ytiam , Can you please assign this issue to me. I would love to work on this.

**Comment by Subham-Maity** [comment]
@JatinSingh08 sure

**Comment by JatinSingh08** [comment]
Hey @Subham-Maity, I'm working on this.  Is that issue actually resolved ?

**Comment by Subham-Maity** [comment]
> Hey @Subham-Maity, I'm working on this. Is that issue actually resolved ?

@JatinSingh08 I have reopened it

**Comment by JatinSingh08** [comment]
Ok thanks shubham.
