### ISSUE TITLE
Replace Audio file with Audio Link 

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#86]
**1. Remove the audio file** 
**2. Add an audio link**

_Note:_  The music must match the theme of our site and also be of a lo-fi type

**Comment by swapn652** [comment]
Yo, Can I work on this? Assign me

**Comment by Subham-Maity** [comment]
@swapn652 Sure!

**Comment by raghavpatidar** [comment]
can i work on this issue? Assign me this please

**Comment by Subham-Maity** [comment]
@raghavpatidar Sure!
