### ISSUE TITLE
Text Show and Disappear Features

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/StockOfSentence#92]
**1. The music starts and stops when you press the spacebar so a text message can be added that says "if you press the space bar music will begin." when we enter the site, then disappears automatic**

**2. We can use an alert also**

**Comment by RXBlade** [comment]
Hey @Subham-Maity , you can assign this task to me.

**Comment by Manoj0Marmat** [comment]
@Subham-Maity i can help with it assign it to me

**Comment by Subham-Maity** [comment]
@Manoj0Marmat Sure!

**Comment by Subham-Maity** [comment]
@RXBlade Sure!

**Comment by RXBlade** [comment]
@Subham-Maity What do you think about my approach?
https://github.com/RXBlade/StockOfSentence

**Comment by RXBlade** [comment]
I also submitted my solution on the pull request

**Comment by Subham-Maity** [comment]
@RXBlade @Manoj0Marmat **My appreciation goes out to both of you for all your work and efforts, and I look forward to working together on this project or another in the future. Your work is amazing, and I appreciate you taking the time to understand the project and spend your valuable time on it.**
